version: '3'

services:

  mysql-dev:
    image: mysql:5.7.22
    environment:
      MYSQL_ROOT_PASSWORD: ciscodisco
      MYSQL_DATABASE: blogapp
    ports:
      - "3306:3306"
    volumes:
      #- "./my.conf:/etc/mysql/conf.d/config-file.cnf"
      - "./data:/var/lib/mysql:rw"

  polr:  
    image: ajanvier/polr
    ports:
     - "9069:80"
    environment:
      DB_HOST: mysql-dev
      DB_PORT: "3306"
      DB_DATABASE: blogapp 
      DB_USERNAME: root
      DB_PASSWORD: ciscodisco
      APP_ADDRESS: "http://172.22.31.104:9069"
      ADMIN_USERNAME: admin
      ADMIN_PASSWORD: admin

  #polr:
  #  image: sahil87/polr
  #  ports:
  #    - "9069:80"

  admin:
    image: adminer
    ports:
      - "8080:8080"

  #yourls:
  #  image: pavlov/yourls
  #  ports:
  #    - "9069:80"
  #  environment:
  #    YOURLS_DB_USER: root
  #    YOURLS_DB_PASS: ciscodisco
  #    YOURLS_DB_NAME: blogapp 
  #    YOURLS_DB_HOST: mysql-dev 
  #    YOURLS_DB_PREFIX: yourls_ 
  #    YOURLS_SITE: "http://172.22.31.104:9069" 
  #    YOURLS_COOKIEKEY: evenmrope
  #    YOURLS_USERS: "root:root"

  #mysql-legacy:
   # image: mysql:5.7.22
    #environment:
    # MYSQL_ROOT_PASSWORD: ciscodisco
    #MYSQL_DATABASE: legacyapp
    #ports:
    #  - "3309:3306"

  #client:
  #  image: mysql:5.7.22
  #  depends_on:
  #   - mysql-dev
  #  command: mysql -uroot -pciscodisco -hmysql-dev blogapp

  